name: "Hikvision-Sip2Rtsp"
description: "Inject RTSP video feed when you forward the call from an indoor station to Asterisk as a TRUNK setup"
version: "1.0"
slug: "hikvision_sip2rtsp"
url: "https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-sip2rtsp"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:ro
