build_from:
  i386: library/ubuntu:22.10
  amd64: library/ubuntu:22.10
  # Hikvision SDK requires this particular base os to run on aarch64 machines (RPi)
  aarch64: openeuler/openeuler:22.03-lts-sp1
